[package]
name = "asm-playground"
version = "0.1.0"
authors = ["Andrey Torsunov <andrey.torsunov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
